export default function () {
  return [
    {
      title: 'Title',
      url: 'blank.wav',
      id: 'm0',
      v: 0,
      blank: true,
    },
    {
      title: '9 + 10 = 21',
      url: '9+10=21.mp3',
      id: 'm1',
      v: 1,
      blank: false,
    },
    {
      title: 'Aint Nobody Got Time',
      url: 'nobodyGotTime.wav',
      id: 'm2',
      v: 2,
      blank: false,
    },
    {
      title: 'Another One DJ Khaled',
      url: 'anotherOne.wav',
      id: 'm3',
      v: 3,
      blank: false,
    },
    {
      title: 'Barely',
      url: 'barely.mp3',
      id: 'm4',
      v: 4,
      blank: false,
    },
    {
      title: 'Blastoise Kid',
      url: 'blastoise.MP3',
      id: 'm5',
      v: 5,
      blank: false,
    },
    {
      title: 'Bruh',
      url: 'bruh.wav',
      id: 'm6',
      v: 6,
      blank: false,
    },
    {
      title: 'Catch Me Outside',
      url: 'howBoutDat.wav',
      id: 'm7',
      v: 7,
      blank: false,
    },
    {
      title: 'Damn Daniel',
      url: 'damnDaniel.wav',
      id: 'm8',
      v: 8,
      blank: false,
    },
    {
      title: 'Deez Nuts',
      url: 'deezNuts.wav',
      id: 'm9',
      v: 9,
      blank: false,
    },
    {
      title: 'Evil Laugh',
      url: 'evilLaugh.wav',
      id: 'm10',
      v: 10,
      blank: false,
    },
    {
      title: 'Filthy Animal Home Alone',
      url: 'filthyAnimal.mp3',
      id: 'm11',
      v: 11,
      blank: false,
    },
    {
      title: 'Fun To Do Bad Things',
      url: 'badThings.wav',
      id: 'm12',
      v: 12,
      blank: false,
    },
    {
      title: 'Gayyyy',
      url: 'gayyyy.wav',
      id: 'm13',
      v: 13,
      blank: false,
    },
    {
      title: 'Goat',
      url: 'goat.mp3',
      id: 'm14',
      v: 14,
      blank: false,
    },
    {
      title: 'HAHA SHUTUP',
      url: 'hahaShutUp.mp3',
      id: 'm15',
      v: 15,
      blank: false,
    },
    {
      title: 'Hell Naw',
      url: 'hellNaw.mp3',
      id: 'm16',
      v: 16,
      blank: false,
    },
    {
      title: 'Homer Simpson Boring',
      url: 'homerBoring.mp3',
      id: 'm17',
      v: 17,
      blank: false,
    },
    {
      title: 'Hoodrat Stuff',
      url: 'hoodRatStuff.wav',
      id: 'm18',
      v: 18,
      blank: false,
    },
    {
      title: 'I Like Trains',
      url: 'iLikeTrains.mp3',
      id: 'm19',
      v: 19,
      blank: false,
    },
    {
      title: 'I Like Turtles',
      url: 'iLikeTurtles.wav',
      id: 'm20',
      v: 20,
      blank: false,
    },
    {
      title: 'I Yanked The Thing',
      url: 'yankedTheThing.wav',
      id: 'm21',
      v: 21,
      blank: false,
    },
    {
      title: 'Is This Real Life',
      url: 'isThisRealLife.wav',
      id: 'm22',
      v: 22,
      blank: false,
    },
    {
      title: 'Leeroy Jenkins',
      url: 'leeroyJenkins.wav',
      id: 'm23',
      v: 23,
      blank: false,
    },
    {
      title: 'Legally Blind',
      url: 'legallyBlind.mp3',
      id: 'm24',
      v: 24,
      blank: false,
    },
    {
      title: 'Man Jumps Off Bridge',
      url: 'jumpOffBridgeMeme.wav',
      id: 'm25',
      v: 25,
      blank: false,
    },
    {
      title: 'Ohhhhh Supa Hot Fire',
      url: 'ohhhhh.wav',
      id: 'm26',
      v: 26,
      blank: false,
    },
    {
      title: 'Oh Hell No',
      url: 'ohHellNo.mp3',
      id: 'm27',
      v: 27,
      blank: false,
    },
    {
      title: 'Pew Pew',
      url: 'pewPew.mp3',
      id: 'm28',
      v: 28,
      blank: false,
    },
    {
      title: 'Pika Pika',
      url: 'pikachuPikaPika.mp3',
      id: 'm29',
      v: 29,
      blank: false,
    },
    {
      title: 'Sad Trombone',
      url: 'sadTrombone.wav',
      id: 'm30',
      v: 30,
      blank: false,
    },
    {
      title: 'Sad Violin',
      url: 'sadViolin.wav',
      id: 'm31',
      v: 31,
      blank: false,
    },
    {
      title: 'That Was Legitness',
      url: 'thatWasLegitness.mp3',
      id: 'm32',
      v: 32,
      blank: false,
    },
    {
      title: 'This Is Sparta',
      url: 'thisIsSparta.wav',
      id: 'm33',
      v: 33,
      blank: false,
    },
    {
      title: 'Weather Boy',
      url: 'weatherBoy.wav',
      id: 'm34',
      v: 34,
      blank: false,
    },
    {
      title: 'Wet Fart',
      url: 'wetFart.mp3',
      id: 'm35',
      v: 35,
      blank: false,
    },
    {
      title: 'What Are Those',
      url: 'whatAreThose.wav',
      id: 'm36',
      v: 36,
      blank: false,
    },
    {
      title: 'Why You Mad',
      url: 'whyYouHaveToBeMad.mp3',
      id: 'm37',
      v: 37,
      blank: false,
    },
    {
      title: 'Yeah Boy',
      url: 'yeahBoy.mp3',
      id: 'm38',
      v: 38,
      blank: false,
    },
    {
      title: 'You Are A Loser',
      url: 'youarealoser.wav',
      id: 'm39',
      v: 39,
      blank: false,
    },
    {
      title: 'You Guys Are Trash',
      url: 'youGuysAreTrash.mp3',
      id: 'm40',
      v: 40,
      blank: false,
    },
    {
      title: 'You Mad Bro',
      url: 'youMadBro.mp3',
      id: 'm41',
      v: 41,
      blank: false,
    },
  ];
}
