export default function () {
  return [
    {
      title: 'Title',
      url: 'blank.wav',
      id: 'm0',
      v: 0,
      blank: true,
    },
    {
      title: 'Deez Nuts',
      url: 'deezNuts.wav',
      id: 'm1',
      v: 1,
      blank: false,
    },
    {
      title: 'Catch Me Outside',
      url: 'howBoutDat.wav',
      id: 'm2',
      v: 2,
      blank: false,
    },
    {
      title: 'Man Jumps Off Bridge',
      url: 'jumpOffBridgeMeme.wav',
      id: 'm3',
      v: 3,
      blank: false,
    },
    {
      title: 'Sad Violin',
      url: 'sadViolin.wav',
      id: 'm4',
      v: 4,
      blank: false,
    },
    {
      title: 'Fun To Do Bad Things',
      url: 'badThings.wav',
      id: 'm5',
      v: 5,
      blank: false,
    },
    {
      title: 'Hoodrat Stuff',
      url: 'hoodRatStuff.wav',
      id: 'm6',
      v: 6,
      blank: false,
    },
    {
      title: 'I Like Turtles',
      url: 'iLikeTurtles.wav',
      id: 'm7',
      v: 7,
      blank: false,
    },
    {
      title: 'Is This Real Life',
      url: 'isThisRealLife.wav',
      id: 'm8',
      v: 8,
      blank: false,
    },
    {
      title: 'Leeroy Jenkins',
      url: 'leeroyJenkins.wav',
      id: 'm9',
      v: 9,
      blank: false,
    },
    {
      title: 'Ohhhhh',
      url: 'ohhhhh.wav',
      id: 'm10',
      v: 10,
      blank: false,
    },
    {
      title: 'This Is Sparta',
      url: 'thisIsSparta.wav',
      id: 'm11',
      v: 11,
      blank: false,
    },
    {
      title: 'Weather Boy',
      url: 'weatherBoy.wav',
      id: 'm12',
      v: 12,
      blank: false,
    },
    {
      title: 'I Yanked The Thing',
      url: 'yankedTheThing.wav',
      id: 'm13',
      v: 13,
      blank: false,
    },
    {
      title: 'Damn Daniel',
      url: 'damnDaniel.wav',
      id: 'm14',
      v: 14,
      blank: false,
    },
      title: 'Gayyyy',
      url: 'gayyyy.wav',
      id: 'm15',
      v: 15,
      blank: false,
    },
      title: 'You Are A Loser',
      url: 'youarealoser.wav',
      id: 'm16',
      v: 16,
      blank: false,
    },
  ];
}
